### ISSUE TITLE
Elements R3D4 (Abaqus) are not recognized in Damask code.

### ISSUE THREAD

**Issue by DavidMercier** [stabix/stabix#39]
Possibility to avoid this problem, by switching off the ping pong in DAMASK or to set "num_threads" to 1...

**Comment by DavidMercier** [comment]
Possibility to avoid this problem, by switching off the ping pong in DAMASK or to set "num_threads" to 1...

**Comment by DavidMercier** [comment]
To switch off the ping pong in DAMASK, just set to 0 the variable usePingPong in the file : Damask/Code/numerics.f90

To set DAMASK_NUM_THREADS to 1, which is an environment variable, change directly the value of this variable in the DAMASK_env file in your Damask repository, or just write this in your terminal before to run Abaqus :
bash> export DAMASK_NUM_THREADS=1
 csh> setenv DAMASK_NUM_THREADS 1

**Comment by DavidMercier** [comment]
Damask is not working anymore with Abaqus in 2022; https://damask.mpie.de/

**Comment by Gaolejiang** [comment]
Hi David,
I used DAMASK2.0.3 and stabix to simulate nanoindentation ,I try your recommand 'export DAMASK_NUM_THREADS=1' ,also modify numerics.f90, but it still say' unknow element type' r3d4. What should Ido ?

**Comment by DavidMercier** [comment]
Hi, I don't really have a solution for you sorry. Do you manage to generate at least the SX or BX model for Abaqus using the python routine? You can maybe try to ask directly to the Damask team or check these questions on RG: 
- https://www.researchgate.net/post/How_to_use_DAMASK_crystal_plasticity_codes_as_a_UMAT_for_ABAQUS_simulation
- https://www.researchgate.net/post/Error_using_DAMASK_crystal_plasticity_codes_as_a_UMAT_for_ABAQUS_FEM_simulation
Good luck

**Comment by 63Nobody63** [comment]
Sorry to bother you, has this issue been solved? I'm also experiencing this trouble, if it is resolved, please be sure to let me know, thank you

**Comment by DavidMercier** [comment]
No answer on RG: https://www.researchgate.net/post/R3D4_element_of_damask203
Sorry, no update since 2023 on this bug? And given Abaqus is not proposed anymore as a solver for DAMASK: https://damask-multiphysics.org/documentation/usage.html#id1, I advise to change for one of the proposed solver.
