### ISSUE TITLE
Bug with the load of .ang file and with calculations using MTEX functions, when it's a 2 phases material...

### ISSUE THREAD

**Issue by DavidMercier** [stabix/stabix#48]

**Comment by DavidMercier** [comment]
bug too with 1 phase indexed (0) and with not indexed pixels (-1)...

**Comment by GTerHaar** [comment]
Any update on this bug?

Is it possible to import .ctf format using the the MTEX import? I am getting an error msg:

Warning: Please reload your data and save it as a variable named ebsd ! 
> In warning_commwin at 15 

I am assuming that this is the same bug as mentioned above?
regards

**Comment by DavidMercier** [comment]
Hi, I think it is possible to import .ctf file with MTEX.  Anyway i think .ang file is better to use. But the warning you have is related to the last step in the 'import_wizard' of the MTEX toolbox. Before you close the import_wizard window, you must save your data as a variable named 'ebsd', in order to plot something in the stabix toolbox. The problem I mention above is about the number of phases. If you have more than 1 phase material it is not yet possible to use MTEX functions in the stabix toolbox...  good luck. Let me know if you have others issues or questions. David

**Comment by DavidMercier** [comment]
Debugged for .ctf file with 2 phases material...
See commit 8041e3f915924c34dd253a4a39e5de0c764ccd91

**Comment by DavidMercier** [comment]
OK with . ang file also but checks to do for left and right grains...
