### ISSUE TITLE
Adding to documentation: mtex_convert2TSLdata

### ISSUE THREAD

**Issue by MGRashed** [stabix/stabix#70]
Just a request to add the procedure description of using **_mtex_convert2TSLdata_** in this page of the documentation - https://stabix.readthedocs.io/en/latest/experimental_data.html

Example: To get GF2 and RB files, execute the below command in MATLAB command window after processing (cropping, cleaning, filling etc.) the EBSD data in MTEX -

_mtex_convert2TSLdata(ebsd, 5, 1)_

**Comment by DavidMercier** [comment]
I wrote a paragraph about that in the doc: 
https://github.com/stabix/stabix/blob/master/doc/experimental_data.rst

You can always propose some inputs and new documentation via Github and push them to the main repository (pull requests). Then you collaborate on the project...

**Comment by MGRashed** [comment]
_mtex_convert2TSLdata(ebsd, 5, 1)_

In the above code, 5 means the angle and 1 means the phase number?

**Comment by DavidMercier** [comment]
If you look into the matlab file, usually arguments are described in the top comments...
Here in this function, it is:
% ebsd: MTEX structure variable
% angle_value: A grain is defined as a region, in which the misorientation of neighbored measurements is less than the given angle.

I don't see for the 1. Where have you seen this example line (mtex_convert2TSLdata(ebsd, 5, 1))? Thanks

**Comment by MGRashed** [comment]
_mtex_convert2TSLdata(ebsd, angle)_ is the correct command? I have been doing it wrong.

In MTEX, it is possible to segment grains by two methods, segmentation angle or unit cell -

angle: [grains,ebsd.grainId,ebsd.mis2mean] = calcGrains(ebsd,'angle',5*degree);
unit cell: [grains,ebsd.grainId] = calcGrains(ebsd('indexed'),'unitcell');

With the _mtex_convert2TSLdata(ebsd, angle)_ command, sometimes I am missing some of the grains that are visible in MTEX. Is there a way we can use the "unit cell" approach that will detect all grains?

**Comment by DavidMercier** [comment]
I've changed now with the following function:
_mtex_convert2TSLdata(ebsd, method)_

If you want angle misorientation, you write: 
_mtex_convert2TSLdata(ebsd, 5)_

and if you want 'unitcell' method:
_mtex_convert2TSLdata(ebsd, 'unitcell')_

I think you are tight for _mtex_convert2TSLdata(ebsd, 5, 1)_, but I removed this argument in the function and it is useless now...Coordiante system is set from the popupmenu when you run MTEX data loading into the GUI...
