### ISSUE TITLE
 Error while evaluating uicontrol Callback

### ISSUE THREAD

**Issue by solerzhuxy** [stabix/stabix#74]
System configuration: win10 &  MATLAB2014a. Stabix works well in Single Crystal Indentation GUI only. 
Results of "write to CPFEM input files" come out in Single Crystal Scratch as follows:
![image](https://user-images.githubusercontent.com/44295509/55148463-37c90f80-5183-11e9-8b8c-084c656062cd.png)
I find that chaos window happens with even clickling "abaqus2012" in BX Scratch and BX indentation GUIs.
The errors in Matlab command window :
![image](https://user-images.githubusercontent.com/44295509/55148666-9a221000-5183-11e9-83b0-fe0ddac9d3e0.png)
What is wrong here？

**Comment by solerzhuxy** [comment]
ps：Python 2.7.10，mtex-5.1.1.

**Comment by DavidMercier** [comment]
Thanks for your feedback, sounds like an error related to Matlab version. Could you let me know what is the top of the error message in the Matlab command window?

**Comment by solerzhuxy** [comment]
Error message：

——————————————————
属性名称已被此类或其某个超类使用。The property name has been used by this class or one of its superclasses.
出错 scribe.legend/init (line 70)
    l = schema.prop(handle(fig),'ScribeLegendListeners','MATLAB array');
出错 scribe.legend (line 122)
  h.init();
出错 legend>make_legend (line 381)
lh=scribe.legend(ha,orient,location,position,children,listen,strings,propargs{:});
出错 legend (line 284)
            [h,msg] = make_legend(ha,varargin(arg:end));
出错 preCPFE_indentation_setting_BX (line 360)
    legend(strcat('Grain n�', num2str(gdata.GB.activeGrain)), ...
出错 preCPFE_generate_indentation_model_BX (line 18)
preCPFE_indentation_setting_BX;
出错 preCPFE_generate_CPFE_model (line 17)
    preCPFE_generate_indentation_model_BX;
Error while evaluating uicontrol Callback
——————————————————

If click ABAQUS2012 as output format, errors writes:

______________________________________________
引用了不存在的字段 References to fields that do not exist  'box_bias_conv_x_val'。
出错 preCPFE_preset_bias_parameters_SX (line 17)
    set(gui_SX.handles.mesh.box_bias_conv_x_val, 'String', num2str(gui_SX.defaults.variables.box_bias_conv_x_abaqus));
Error while evaluating uicontrol Callback
______________________________________________

After commenting line 360-361, 363-366, GUIs work well with correct output files done and GUI keep its original  layout without disorder  while the error in  line17 exists also. It seems that the line 360 for legend  in preCPFE_generate_indentation_model_BX and the line 17, 18 for tests in preCPFE_preset_bias_parameters_SX do not significantly affect the output.
Thanks for your help.

**Comment by DavidMercier** [comment]
Sounds great. Not resolved, but from my point of view bug only related to Matlab version. No need to change drastically the code... Thanks for your feedback.
